HomePage/urls.py
from django.urls import path
from . import views

app_name = 'HomePage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.loginpage, name='loginpage'),
    path('logout/', views.logout, name='logout')
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomePage.urls', namespace='HomePage')),
]

HomePage/models.py
from django.db import models

# Create your models here.

HomePage/forms.py
from django import forms

class input_login (forms.Form):
    input_username = forms.CharField("Username", min_length=1)
    input_password = forms.CharField("Password", min_length=8)

HomePage/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

# Create your views here.
def homepage(request):
    return render(request,'index.html')

def loginpage(request):
    if(request.user is not None):
        if request.user.is_authenticated:
            return redirect('HomePage:homepage')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            request.session['login_timestamp'] = str(datetime.now())
            return redirect('HomePage:homepage')
        else:
            return render(request, 'login.html', {
                'error' : True
            })        

    return render(request, 'login.html')

def logout(request):
    request.session.flush()
    auth_logout(request)
    return redirect('HomePage:homepage')

HomePage/templates/index.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}

<div style="padding-bottom: 10px;">
    {% if user.is_authenticated %}
    <small> Logged In,<a href="{% url 'HomePage:logout' %}"> click here to log out</a> </small>
    {% else %}
    <small>You are not logged in yet,<a href="{% url 'HomePage:loginpage' %}"> click here to log in</a></small>
    {% endif %}
</div>

<div style="text-align: center; padding: 20px;">
    {% if user.is_authenticated %}
        <h3>Good
        {% now "H" as current_time %}
        {% if current_time|add:"0" >= 18 %}
            evening 
        {% elif current_time|add:"0" >= 12 %}
            afternoon 
        {% else %}
            morning 
        {% endif %}
        {{user.first_name}} {{user.last_name}}</h3>
        <br>
        <p>Log in time at {{ request.session.login_timestamp }}</p>
    {% else %}
    <h3>Good
        {% now "H" as current_time %}
        {% if current_time|add:"0" >= 18 %}
            evening 
        {% elif current_time|add:"0" >= 12 %}
            afternoon 
        {% else %}
            morning 
        {% endif %}
        Random Stranger</h3>
    {% endif %}
</div>


{% endblock %}

HomePage/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <title>Story 09</title>
</head>
<body>
    <small style="padding-left: 6px;"><a href="{% url 'HomePage:homepage' %}">Back to Home Page</a></small>
    <div><h2 style="text-align: center;">Login Page</h2></div>
    <div class="container" style="padding-top: 50px;">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="exampleInputEmail1">Username</label>
              <input type="text" class="form-control" name="username" placeholder="Username">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" name="password" placeholder="Password" minlength="8">
              <small id="emailHelp" class="form-text text-muted">We'll never share your password to the Chinese.</small>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    {% if error %}
        <div style="text-align: center; padding-top: 10px;">
            <h5 style="color: red;">Invalid Username/Password</h5>
        </div>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</body>
</html>

HomePage/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <title>Story 09</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Story 09</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'HomePage:homepage' %}">Home</a>
          </div>
          <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Login</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'HomePage:loginpage' %}">Login</a>
              {% endif %}
            </div>
        </div>
      </nav>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</body>
</html>